name: developer_mode
description: A Flutter plugin to detect jailbreak/root status and developer mode/emulator on Android and iOS devices.
version: 0.0.2
homepage: https://github.com/krishnapalsendhav/developer_mode
repository: https://github.com/krishnapalsendhav/developer_mode
issue_tracker: https://github.com/krishnapalsendhav/developer_mode/issues

topics:
  - security
  - jailbreak
  - root
  - developer-mode
  - emulator

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.krishnapal.developerMode
        pluginClass: FlutterJailbreakDetectionPlugin
      ios:
        pluginClass: DeveloperModePlugin