org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official

# Enable 16KB page size support
android.experimental.lint.missingBaselineIsEmptyBaseline=true
android.nonTransitiveRClass=true
android.nonFinalResIds=true
